name: bluesky_awsnews_bot

environment:
  sdk: ^3.3.4

dependencies:
  aws_lambda_dart_runtime_ns: ^0.0.13
  bluesky: ^0.15.18
  bluesky_text: ^0.6.9
  dart_rss: ^3.0.3
  http: '>=0.13.1 <2.0.0'
  intl: '>=0.17.0 <0.20.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependency_overrides:
  http: '>=0.13.1 <2.0.0'
  intl: '>=0.17.0 <0.20.0'