service: bluesky-bot-awsnews

custom:
  postSchedule: cron(0 13-23 ? * MON-FRI *)

provider:
  name: aws
  runtime: provided
  timeout: 30
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/arm64
  architecture: arm64
  environment:
    BLUESKY_AWSNEWS_IDENTIFIER: ${env:BLUESKY_AWSNEWS_IDENTIFIER}
    BLUESKY_AWSNEWS_PASSWORD: ${env:BLUESKY_AWSNEWS_PASSWORD}

functions:
  aws:
    image:
      name: appImage
      command:
        - aws
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  architecture:
    image:
      name: appImage
      command:
        - architecture
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  apn:
    image:
      name: appImage
      command:
        - apn
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  awsMarketplace:
    image:
      name: appImage
      command:
        - awsMarketplace
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  bigData:
    image:
      name: appImage
      command:
        - bigData
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  awsInsights:
    image:
      name: appImage
      command:
        - awsInsights
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  smb:
    image:
      name: appImage
      command:
        - smb
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  businessProductivity:
    image:
      name: appImage
      command:
        - businessProductivity
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  businessIntelligence:
    image:
      name: appImage
      command:
        - businessIntelligence
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  compute:
    image:
      name: appImage
      command:
        - compute
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  contactCenter:
    image:
      name: appImage
      command:
        - contactCenter
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  containers:
    image:
      name: appImage
      command:
        - containers
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  database:
    image:
      name: appImage
      command:
        - database
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  desktopAndApplicationStreaming:
    image:
      name: appImage
      command:
        - desktopAndApplicationStreaming
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  developer:
    image:
      name: appImage
      command:
        - developer
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  devops:
    image:
      name: appImage
      command:
        - devops
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  enterpriseStrategy:
    image:
      name: appImage
      command:
        - enterpriseStrategy
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  awsCloudFinancialManagement:
    image:
      name: appImage
      command:
        - awsCloudFinancialManagement
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  gameTech:
    image:
      name: appImage
      command:
        - gameTech
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  hpc:
    image:
      name: appImage
      command:
        - hpc
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  infrastructureAndAutomation:
    image:
      name: appImage
      command:
        - infrastructureAndAutomation
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  industries:
    image:
      name: appImage
      command:
        - industries
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  iot:
    image:
      name: appImage
      command:
        - iot
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  machineLearning:
    image:
      name: appImage
      command:
        - machineLearning
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  mt:
    image:
      name: appImage
      command:
        - mt
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  media:
    image:
      name: appImage
      command:
        - media
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  messagingAndTargeting:
    image:
      name: appImage
      command:
        - messagingAndTargeting
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  modernizingWithAws:
    image:
      name: appImage
      command:
        - modernizingWithAws
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  ibmRedhat:
    image:
      name: appImage
      command:
        - ibmRedhat
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  dotnet:
    image:
      name: appImage
      command:
        - dotnet
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  mobile:
    image:
      name: appImage
      command:
        - mobile
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  networkingAndContentDelivery:
    image:
      name: appImage
      command:
        - networkingAndContentDelivery
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  openSource:
    image:
      name: appImage
      command:
        - openSource
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  publicsector:
    image:
      name: appImage
      command:
        - publicsector
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  quantumComputing:
    image:
      name: appImage
      command:
        - quantumComputing
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  robotics:
    image:
      name: appImage
      command:
        - robotics
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  awsForSap:
    image:
      name: appImage
      command:
        - awsForSap
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  security:
    image:
      name: appImage
      command:
        - security
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  spacial:
    image:
      name: appImage
      command:
        - spacial
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  startups:
    image:
      name: appImage
      command:
        - startups
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  storage:
    image:
      name: appImage
      command:
        - storage
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  supplyChain:
    image:
      name: appImage
      command:
        - supplyChain
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
  trainingAndCertification:
    image:
      name: appImage
      command:
        - trainingAndCertification
    events:
      - eventBridge:
          schedule: ${self:custom.postSchedule}
