service: bluesky-bot-awsnews

provider:
  name: aws
  runtime: provided
  timeout: 30
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/arm64
  architecture: arm64
  environment:
    BLUESKY_AWSNEWS_IDENTIFIER: ${env:BLUESKY_AWSNEWS_IDENTIFIER}
    BLUESKY_AWSNEWS_PASSWORD: ${env:BLUESKY_AWSNEWS_PASSWORD}

custom:
  crawlSchedule: cron(0 13-22 ? * MON-FRI *)

functions:
  awsFeed:
    image:
      name: appImage
      command:
        - awsFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  architectureFeed:
    image:
      name: appImage
      command:
        - architectureFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  awsCostManagementFeed:
    image:
      name: appImage
      command:
        - awsCostManagementFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  apnFeed:
    image:
      name: appImage
      command:
        - apnFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  awsMarketplaceFeed:
    image:
      name: appImage
      command:
        - awsMarketplaceFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  bigDataFeed:
    image:
      name: appImage
      command:
        - bigDataFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  businessProductivityFeed:
    image:
      name: appImage
      command:
        - businessProductivityFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  computeFeed:
    image:
      name: appImage
      command:
        - computeFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  contactCenterFeed:
    image:
      name: appImage
      command:
        - contactCenterFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  containersFeed:
    image:
      name: appImage
      command:
        - containersFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  databaseFeed:
    image:
      name: appImage
      command:
        - databaseFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  desktopAndApplicationStreamingFeed:
    image:
      name: appImage
      command:
        - desktopAndApplicationStreamingFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  developerFeed:
    image:
      name: appImage
      command:
        - developerFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  devopsFeed:
    image:
      name: appImage
      command:
        - devopsFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  enterpriseStrategyFeed:
    image:
      name: appImage
      command:
        - enterpriseStrategyFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  gameTechFeed:
    image:
      name: appImage
      command:
        - gameTechFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  hpcFeed:
    image:
      name: appImage
      command:
        - hpcFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  infrastructureAndAutomationFeed:
    image:
      name: appImage
      command:
        - infrastructureAndAutomationFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  industriesFeed:
    image:
      name: appImage
      command:
        - industriesFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  iotFeed:
    image:
      name: appImage
      command:
        - iotFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  machineLearningFeed:
    image:
      name: appImage
      command:
        - machineLearningFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  mtFeed:
    image:
      name: appImage
      command:
        - mtFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  mediaFeed:
    image:
      name: appImage
      command:
        - mediaFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  messagingAndTargetingFeed:
    image:
      name: appImage
      command:
        - messagingAndTargetingFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  modernizingWithAwsFeed:
    image:
      name: appImage
      command:
        - modernizingWithAwsFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  mobileFeed:
    image:
      name: appImage
      command:
        - mobileFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  networkingAndContentDeliveryFeed:
    image:
      name: appImage
      command:
        - networkingAndContentDeliveryFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  openSourceFeed:
    image:
      name: appImage
      command:
        - openSourceFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  publicsectorFeed:
    image:
      name: appImage
      command:
        - publicsectorFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  quantumComputingFeed:
    image:
      name: appImage
      command:
        - quantumComputingFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  roboticsFeed:
    image:
      name: appImage
      command:
        - roboticsFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  awsForSapFeed:
    image:
      name: appImage
      command:
        - awsForSapFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  securityFeed:
    image:
      name: appImage
      command:
        - securityFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  startupsFeed:
    image:
      name: appImage
      command:
        - startupsFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
  trainingAndCertificationFeed:
    image:
      name: appImage
      command:
        - trainingAndCertificationFeed
    events:
      - eventBridge:
          schedule: ${self:custom.crawlSchedule}
