enum Feed {
  aws('aws'),
  architecture('architecture'),
  apn('apn'),
  awsMarketplace('awsmarketplace'),
  bigData('big-data'),
  awsInsights('aws-insights'),
  smb('smb'),
  businessProductivity('business-productivity'),
  businessIntelligence('business-intelligence'),
  compute('compute'),
  contactCenter('contact-center'),
  containers('containers'),
  database('database'),
  desktopAndApplicationStreaming('desktop-and-application-streaming'),
  developer('developer'),
  devops('devops'),
  enterpriseStrategy('enterprise-strategy'),
  awsCloudFinancialManagement('aws-cloud-financial-management'),
  gameTech('gametech'),
  hpc('hpc'),
  infrastructureAndAutomation('infrastructure-and-automation'),
  industries('industries'),
  iot('iot'),
  machineLearning('machine-learning'),
  mt('mt'),
  media('media'),
  messagingAndTargeting('messaging-and-targeting'),
  modernizingWithAws('modernizing-with-aws'),
  ibmRedhat('ibm-redhat'),
  dotnet('dotnet'),
  mobile('mobile'),
  networkingAndContentDelivery('networking-and-content-delivery'),
  openSource('opensource'),
  publicsector('publicsector'),
  quantumComputing('quantum-computing'),
  robotics('robotics'),
  awsForSap('awsforsap'),
  security('security'),
  spacial('spatial'),
  startups('startups'),
  storage('storage'),
  supplyChain('supply-chain'),
  trainingAndCertification('training-and-certification');

  final String path;

  String get uri => 'https://aws.amazon.com/blogs/$path/feed';

  const Feed(this.path);
}
